include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
    - linter
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.gql.dart
    - lib/graphql/
    - lib/grpc/generated/**
    - lib/**.freezed.dart
    - lib/**.gen.dart
    - lib/graphql/__generated__/serializers.gql.dart
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 100
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
  rules-exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.gql.dart
    - lib/graphql/**
    - lib/grpc/generated/**
    - lib/**.freezed.dart
    - lib/**.gen.dart
    - lib/graphql/__generated__/serializers.gql.dart
  metrics-exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.gql.dart
    - lib/graphql/**
    - lib/grpc/generated/**
    - lib/**.freezed.dart
    - lib/**.gen.dart
    - lib/graphql/__generated__/serializers.gql.dart
