name: github_repository_search
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter_screenutil: ^5.6.1
  flutter_gen_runner: ^5.2.0
  logger: ^1.1.0
  flutter_riverpod: ^2.3.1
  gap: ^2.0.1
  shared_preferences: ^2.0.17
  flutter_platform_widgets: ^2.2.6
  fluttertoast: ^8.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    # translations
    - assets/translations/

  fonts:
  - family: NotoSansJP
    fonts:
      - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
      - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Bold.otf
        weight: 700
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        weight: 700
